[build]
  command = "npm run build"
  publish = ".next"

# Next.js 插件配置 - 确保支持 App Router API Routes
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers 配置
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# 构建环境变量
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"